import { readdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

function getLibraryApiSidebar() {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);

  return readdirSync(resolve(__dirname, '../../library-sources'));
}

const libraries = getLibraryApiSidebar();

export const LIBRARY_API_SIDEBAR = libraries.map(item => {
  return {
    type: 'autogenerated',
    label: item,
    dirName: `library-api/${item}`,
    href: `/docs/library-api/${item}`,
    sidebarId: `${item}Sidebar`
  }
});