import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import { LIBRARY_API_SIDEBAR } from './config/constant'

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: 'default'
    }
  ]
};

LIBRARY_API_SIDEBAR.forEach(item => {
  Object.assign(sidebars, {
    [item.sidebarId]: [{
      type: 'autogenerated',
      dirName: item.dirName
    }]
  });
});

export default sidebars;
